g++ -o port -lncurses -pthread ../main.cpp ../Port.cpp ../Buffer.cpp ../Container.cpp ../Dock.cpp ../Orders.cpp ../Ship.cpp
# ../Port.cpp ../Buffer.cpp ../Conteiner.cpp ../Dock.cpp ../Orders.cpp ../Railway.cpp ../Ship.cpp ../Train.cpp ../TrainStation.cpp
